// Mapa nome do ícone / tipo de botão → ícone.
// Adaptado de Montra (getButtonIcon). Usa @tabler/icons-react (já dependência
// da VitrinePro) porque o lucide-react 1.x removeu os ícones de marca.

import {
  IconMessageCircle,
  IconBrandWhatsapp,
  IconBrandInstagram,
  IconBrandFacebook,
  IconBrandTiktok,
  IconBrandYoutube,
  IconBrandLinkedin,
  IconBrandTelegram,
  IconBrandX,
  IconBrandThreads,
  IconBrandPinterest,
  IconBrandDiscord,
  IconBrandTwitch,
  IconBrandSpotify,
  IconBrandSnapchat,
  IconBrandGoogle,
  IconBrandGoogleMaps,
  IconWorld,
  IconMapPin,
  IconStar,
  IconShoppingBag,
  IconMail,
  IconPhone,
  IconDeviceMobile,
  IconQrcode,
  IconCreditCard,
  IconCurrencyDollar,
  IconCalendar,
  IconCalendarCheck,
  IconCalendarEvent,
  IconFileText,
  IconRobot,
  IconBook,
  IconLink,
  IconExternalLink,
  IconMinus,
  type Icon,
} from "@tabler/icons-react";
import type { ButtonType } from "@/types/buttons";

const BY_TYPE: Partial<Record<ButtonType, Icon>> = {
  whatsapp: IconBrandWhatsapp,
  instagram: IconBrandInstagram,
  facebook: IconBrandFacebook,
  tiktok: IconBrandTiktok,
  youtube: IconBrandYoutube,
  linkedin: IconBrandLinkedin,
  telegram: IconBrandTelegram,
  twitter: IconBrandX,
  threads: IconBrandThreads,
  pinterest: IconBrandPinterest,
  discord: IconBrandDiscord,
  twitch: IconBrandTwitch,
  spotify: IconBrandSpotify,
  snapchat: IconBrandSnapchat,
  google_business: IconBrandGoogle,
  google_maps: IconBrandGoogleMaps,
  google_reviews: IconStar,
  website: IconWorld,
  online_store: IconShoppingBag,
  email: IconMail,
  call: IconPhone,
  mbway: IconDeviceMobile,
  pix: IconQrcode,
  stripe: IconCreditCard,
  paypal: IconCurrencyDollar,
  manychat: IconRobot,
  calendly: IconCalendarCheck,
  google_calendar: IconCalendarEvent,
  form: IconFileText,
  book: IconCalendar,
  catalog: IconBook,
  divider: IconMinus,
  custom: IconLink,
};

const BY_NAME: Record<string, Icon> = {
  messagesquare: IconMessageCircle,
  messagecircle: IconMessageCircle,
  send: IconBrandTelegram,
  video: IconBrandTiktok,
  globe: IconWorld,
  world: IconWorld,
  mappin: IconMapPin,
  map: IconBrandGoogleMaps,
  star: IconStar,
  shoppingbag: IconShoppingBag,
  mail: IconMail,
  phone: IconPhone,
  smartphone: IconDeviceMobile,
  qrcode: IconQrcode,
  creditcard: IconCreditCard,
  dollarsign: IconCurrencyDollar,
  calendar: IconCalendar,
  calendarcheck: IconCalendarCheck,
  calendardays: IconCalendarEvent,
  filetext: IconFileText,
  bot: IconRobot,
  bookopen: IconBook,
  minus: IconMinus,
  link: IconLink,
  externallink: IconExternalLink,
};

export function getButtonIcon(
  iconName?: string,
  type?: string,
  className = "w-5 h-5 shrink-0",
) {
  const byType = type ? BY_TYPE[type as ButtonType] : undefined;
  const key = (iconName || "").toLowerCase().replace(/[^a-z]/g, "");
  const byName = key ? BY_NAME[key] : undefined;
  const Cmp: Icon = byType ?? byName ?? IconExternalLink;
  return <Cmp className={className} stroke={2} />;
}
